sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jaiswal.a/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jaiswal.a/docker-react npm run test
